# Generated by Django 3.0.6 on 2020-06-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fediverseserver',
            name='sharedInbox',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fediverseuser',
            name='KeyId',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fediverseuser',
            name='URL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='fediverseuser',
            name='featured',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='fediverseuser',
            name='followers',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='fediverseuser',
            name='id',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fediverseuser',
            name='inbox',
            field=models.URLField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fediverseuser',
            name='is_manualFollow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fediverseuser',
            name='outbox',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='fediverseuser',
            name='publicKey',
            field=models.TextField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='privateKey',
            field=models.TextField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='publicKey',
            field=models.TextField(editable=False, unique=True),
        ),
    ]
