# Generated by Django 3.0.6 on 2020-06-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr_sys', '0002_auto_20200602_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fediverseuser',
            name='KeyId',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fediverseuser',
            name='publicKey',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
