# Generated by Django 3.0.7 on 2020-06-05 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fr_sys', '0004_auto_20200603_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post_by', django_currentuser.db.models.fields.CurrentUserField(blank=True, default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
                ('post_by_fed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='fr_sys.FediverseUser')),
            ],
        ),
    ]
