# Generated by Django 3.0.7 on 2020-06-05 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fr_sys', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_by_fed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='fr_sys.FediverseUser'),
        ),
    ]
